tiny-shell: source/runner/add_path.c File Reference
add_path.c File Reference
#include "add_path.h"
#include "../core/io_wrap.h"
#include "../os/operations.h"
#include <limits.h>
#include <stdlib.h>
#include <string.h>
Functions
char * strtok_r_custom (char *str, const char *delim, char **saveptr)
bool in_path_env (const os_char *path_env, const os_char *new_path)
bool add_path (const os_char *new_path)
enum run_result run_add_path (const os_char *new_path)
Function Documentation
add_path()
bool add_path (const os_char * new_path)
Definition at line 74 of file add_path.c.
{
    char buffer[SHRT_MAX];
    unsigned int bufferSize = sizeof(buffer) / sizeof(char);
    if(!get_shell_env("PATH", bufferSize, buffer)) {
        format_error("Fail to get PATH environment variable!\n");
        return false;
    }
    if(in_path_env(buffer, new_path)) {
        format_error("The path %s is already in the PATH environment variable.\n", new_path);
        return false;
    }
    os_char *f_path = formatted_path(new_path);
    strncat(buffer, f_path, strlen(f_path));
    if(!set_shell_env("PATH", buffer)) {
        format_error("Failed to set the PATH environment variable!\n");
        free(f_path);
        return false;
    }
    format_success("PATH environment variable is updated successfully.\n");
    free(f_path);
    return true;
}
References format_error(), format_success(), get_shell_env(), in_path_env(), and set_shell_env().
Referenced by run_add_path().
in_path_env()
bool in_path_env (const os_char * path_env, const os_char * new_path)
Definition at line 57 of file add_path.c.
{
    size_t len = strlen(path_env);
    os_char tmp_path_env[SHRT_MAX];
    strncpy(tmp_path_env, path_env, len);
    tmp_path_env[len] = '\0';
    char *rest = NULL;
    char *token = strtok_r_custom(tmp_path_env, SEPARATOR, &rest);
    while(token != NULL) {
        if(!strcmp(token, new_path)) {
            return true;
        }
        token = strtok_r_custom(NULL, SEPARATOR, &rest);
    }
    return false;
}
References strtok_r_custom().
Referenced by add_path().
run_add_path()
enum run_result run_add_path (const os_char * new_path)
Definition at line 101 of file add_path.c.
{
    return add_path(new_path) ? RUN_OK : RUN_FAILED;
}
References add_path(), RUN_FAILED, and RUN_OK.
Referenced by invoke_runner().
strtok_r_custom()
char * strtok_r_custom (char * str, const char * delim, char ** saveptr)
Definition at line 33 of file add_path.c.
{
    char *token = NULL;
    if(str == NULL) {
        str = *saveptr;
    }
    // Skip leading delimiters
    str += strspn(str, delim);
    if(*str == '\0') {
        return NULL;
    }
    // Find the end of the token
    token = str;
    str = strpbrk(token, delim);
    if(str == NULL) {
        // This token finishes the string
        *saveptr = strchr(token, '\0');
    } else {
        // Terminate the token and update the save pointer
        *str = '\0';
        *saveptr = str + 1;
    }
    return token;
}
Referenced by in_path_env().