tiny-shell: source/core/args.h File Reference
args.h File Reference
#include <stdbool.h>
#include "../os/type.h"
Data Structures
struct args
Result after parsing an arbitrary string.
Functions
bool args_init_from_str (struct args *obj, const os_char *input)
Build args from an input string.
void args_destroy (struct args *obj)
struct args * args_deep_copy (const struct args *obj)
Deep copy the object, including arguments string.
void args_deep_copy_init (struct args *obj, const struct args *source)
Initialize the object by deep copying source
bool is_whitespace (os_char c)
!
Function Documentation
args_deep_copy()
struct args * args_deep_copy (const struct args * obj)
Deep copy the object, including arguments string.
Definition at line 145 of file args.c.
{
    if(!obj) {
        return NULL;
    }
    struct args *res = malloc(sizeof(struct args));
    res->argc = obj->argc;
    res->background = obj->background;
    res->argv = (os_char **)malloc((obj->argc + 1) * sizeof(os_char *));
    for(int i = 0; i < obj->argc; ++i) {
        const unsigned int len = strlen(obj->argv[i]);
        res->argv[i] = malloc((len + 1) * sizeof(os_char));
        memcpy(res->argv[i], obj->argv[i], len * sizeof(os_char));
        res->argv[i][len] = '\0';
    }
    res->argv[obj->argc] = NULL;
    return res;
}
References args::argc, args::argv, and args::background.
args_deep_copy_init()
void args_deep_copy_init (struct args * obj, const struct args * source)
Initialize the object by deep copying source
Definition at line 163 of file args.c.
{
    assert(source != NULL && "Cannot deep copy null");
    obj->argc = source->argc;
    obj->background = source->background;
    obj->argv = (os_char **)malloc((source->argc + 1) * sizeof(os_char *));
    for(int i = 0; i < source->argc; ++i) {
        const unsigned int len = strlen(source->argv[i]);
        obj->argv[i] = malloc((len + 1) * sizeof(os_char));
        memcpy(obj->argv[i], source->argv[i], len * sizeof(os_char));
        obj->argv[i][len] = '\0';
    }
    obj->argv[obj->argc] = NULL;
}
References args::argc, args::argv, and args::background.
Referenced by cmd_init_from_str().
args_destroy()
void args_destroy (struct args * obj)
Definition at line 135 of file args.c.
{
    if(!obj) {
        return;
    }
    for(int i = 0; i < obj->argc; ++i) {
        free(obj->argv[i]);
    }
    free((void *)obj->argv);
}
References args::argc, and args::argv.
Referenced by cmd_destroy(), and cmd_init_from_str().
args_init_from_str()
bool args_init_from_str (struct args * obj, const os_char * input)
Build args from an input string.
Returns
true if initialization succeeded, false otherwise
Definition at line 117 of file args.c.
{
    assert(obj && "NULL input");
    obj->argc = 0;
    obj->argv = NULL;
    obj->background = false;
    os_char *quote_transformed = transform_quotes(input);
    if(!quote_transformed) {
        return false;
    }
    split_by_whitespaces(quote_transformed, obj);
    free(quote_transformed);
    for(int i = 0; i < obj->argc; ++i) {
        re_transform_arg(obj->argv[i]);
    }
    verify_background(obj);
    return true;
}
References args::argc, args::argv, args::background, re_transform_arg(), split_by_whitespaces(), transform_quotes(), and verify_background().
Referenced by cmd_init_from_str().
is_whitespace()
bool is_whitespace (os_char c)
!
Helper function
Definition at line 177 of file args.c.
{
    return c == ' ' || c == '\t' || c == '\n';
}
Referenced by split_by_whitespaces(), and transform_quotes().