tiny-shell: source/core/args.c File Reference
args.c File Reference
#include "args.h"
#include "../core/io_wrap.h"
#include "config.h"
#include <assert.h>
#include <stdlib.h>
#include <string.h>
Macros
#define QUOTATION_MARK_STR "\""
Enumerations
enum { MAGIC_TOKEN = '!' , QUOTATION_MARK = '\"' }
Functions
os_char * transform_quotes (const os_char *str)
Transform whitespaces inside quotes into MAGIC_TOKEN
void split_by_whitespaces (const os_char *str, struct args *buffer)
void verify_background (struct args *args)
void re_transform_arg (os_char *arg)
Transform MAGIC_TOKEN inside arg into space.
bool args_init_from_str (struct args *obj, const os_char *input)
Build args from an input string.
void args_destroy (struct args *obj)
struct args * args_deep_copy (const struct args *obj)
Deep copy the object, including arguments string.
void args_deep_copy_init (struct args *obj, const struct args *source)
Initialize the object by deep copying source
bool is_whitespace (os_char c)
!
Macro Definition Documentation
QUOTATION_MARK_STR
#define QUOTATION_MARK_STR "\""
Definition at line 13 of file args.c.
Referenced by transform_quotes().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
MAGIC_TOKEN
QUOTATION_MARK
Definition at line 9 of file args.c.
     {
    MAGIC_TOKEN = '!',
    QUOTATION_MARK = '\"',
};
Function Documentation
args_deep_copy()
struct args * args_deep_copy (const struct args * obj)
Deep copy the object, including arguments string.
Definition at line 145 of file args.c.
{
    if(!obj) {
        return NULL;
    }
    struct args *res = malloc(sizeof(struct args));
    res->argc = obj->argc;
    res->background = obj->background;
    res->argv = malloc((obj->argc + 1) * sizeof(os_char *));
    for(int i = 0; i < obj->argc; ++i) {
        const unsigned int len = strlen(obj->argv[i]);
        res->argv[i] = malloc((len + 1) * sizeof(os_char));
        memcpy(res->argv[i], obj->argv[i], len * sizeof(os_char));
        res->argv[i][len] = '\0';
    }
    res->argv[obj->argc] = NULL;
    return res;
}
References args::argc, args::argv, and args::background.
args_deep_copy_init()
void args_deep_copy_init (struct args * obj, const struct args * source)
Initialize the object by deep copying source
Definition at line 163 of file args.c.
{
    assert(source != NULL && "Cannot deep copy null");
    obj->argc = source->argc;
    obj->background = source->background;
    obj->argv = malloc((source->argc + 1) * sizeof(os_char *));
    for(int i = 0; i < source->argc; ++i) {
        const unsigned int len = strlen(source->argv[i]);
        obj->argv[i] = malloc((len + 1) * sizeof(os_char));
        memcpy(obj->argv[i], source->argv[i], len * sizeof(os_char));
        obj->argv[i][len] = '\0';
    }
    obj->argv[obj->argc] = NULL;
}
References args::argc, args::argv, and args::background.
Referenced by cmd_init_from_str().
args_destroy()
void args_destroy (struct args * obj)
Definition at line 135 of file args.c.
{
    if(!obj) {
        return;
    }
    for(int i = 0; i < obj->argc; ++i) {
        free(obj->argv[i]);
    }
    free(obj->argv);
}
References args::argc, and args::argv.
Referenced by cmd_destroy(), and cmd_init_from_str().
args_init_from_str()
bool args_init_from_str (struct args * obj, const os_char * input)
Build args from an input string.
Returns
true if initialization succeeded, false otherwise
Definition at line 117 of file args.c.
{
    assert(obj && "NULL input");
    obj->argc = 0;
    obj->argv = NULL;
    obj->background = false;
    os_char *quote_transformed = transform_quotes(input);
    if(!quote_transformed) {
        return false;
    }
    split_by_whitespaces(quote_transformed, obj);
    free(quote_transformed);
    for(int i = 0; i < obj->argc; ++i) {
        re_transform_arg(obj->argv[i]);
    }
    verify_background(obj);
    return true;
}
References args::argc, args::argv, args::background, re_transform_arg(), split_by_whitespaces(), transform_quotes(), and verify_background().
Referenced by cmd_init_from_str().
is_whitespace()
bool is_whitespace (os_char c)
!
Helper function
Definition at line 177 of file args.c.
{
    return c == ' ' || c == '\t' || c == '\n';
}
Referenced by split_by_whitespaces(), and transform_quotes().
re_transform_arg()
void re_transform_arg (os_char * arg)
Transform MAGIC_TOKEN inside arg into space.
Definition at line 108 of file args.c.
{
    const unsigned int len = strlen(arg);
    for(int i = 0; i < len; ++i) {
        if(arg[i] == MAGIC_TOKEN) {
            arg[i] = ' ';
        }
    }
}
References MAGIC_TOKEN.
Referenced by args_init_from_str().
split_by_whitespaces()
void split_by_whitespaces (const os_char * str, struct args * buffer)
Definition at line 52 of file args.c.
{
    os_char **argv = malloc(MAX_ARGC * sizeof(os_char *));
    unsigned int argc = 0;
    bool is_space = true;
    bool was_space = true;
    int start = 0;
    for(int i = 0; true; ++i) {
        is_space = is_whitespace(str[i]) || str[i] == '\0';
        if(is_space && !was_space) {
            if(argc >= MAX_ARGC) {
                format_error("Too many arguments, max number is %u\n", MAX_ARGC);
                break;
            }
            const unsigned int len = (i - 1) - start + 1;
            argv[argc] = malloc(len + 1);
            memcpy(argv[argc], str + start, len);
            argv[argc][len] = '\0';
            argc++;
        }
        if(!is_space && was_space) {
            start = i;
        }
        was_space = is_space;
        if(str[i] == '\0') {
            break;
        }
    }
    argv[argc] = NULL;
    buffer->argc = argc;
    buffer->argv = argv;
}
References args::argc, args::argv, format_error(), is_whitespace(), and MAX_ARGC.
Referenced by args_init_from_str().
transform_quotes()
os_char * transform_quotes (const os_char * str)
Transform whitespaces inside quotes into MAGIC_TOKEN
Definition at line 16 of file args.c.
{
    unsigned int length = 0;
    os_char *res = malloc(strlen(str) + 1);
    bool quote_opened = false;
    for(int i = 0; str[i] != '\0'; ++i) {
        if(str[i] == QUOTATION_MARK) {
            quote_opened = !quote_opened;
        } else if(quote_opened) {
            if(is_whitespace(str[i]))
                res[length] = MAGIC_TOKEN;
            else
                res[length] = str[i];
            length++;
        } else {
            res[length] = str[i];
            length++;
        }
    }
    if(quote_opened) {
        format_error("Number of " QUOTATION_MARK_STR " character is odd\n");
        free(res);
        return NULL;
    }
    res[length] = '\0';
    os_char *tmp = realloc(res, length + 1);
    if(!tmp) {
        format_error("Cannot allocate memory for input args\n");
        free(res);
        return NULL;
    } else {
        return tmp;
    }
}
References format_error(), is_whitespace(), MAGIC_TOKEN, QUOTATION_MARK, and QUOTATION_MARK_STR.
Referenced by args_init_from_str().
verify_background()
void verify_background (struct args * args)
Definition at line 87 of file args.c.
{
    int first_oc = -1;
    for(int i = 0; i < args->argc; ++i) {
        if(strcmp(args->argv[i], "&") == 0) {
            first_oc = i;
            break;
        }
    }
    if(first_oc < 0) {
        args->background = false;
        return;
    }
    free(args->argv[first_oc]);
    for(int i = first_oc + 1; i < args->argc; ++i) {
        args->argv[i - 1] = args->argv[i];
    }
    args->argc--;
    args->background = true;
}
References args::argc, args::argv, and args::background.
Referenced by args_init_from_str().