tiny-shell: source/core/cmd.h File Reference
cmd.h File Reference
#include "../os/type.h"
#include "args.h"
Data Structures
struct cmd
Resulting struct after parsing the input.
Enumerations
enum cmd_type {
CMD_UNKNOWN , CMD_INVALID_SYNTAX , CMD_NOOP , CMD_CHANGE_DIR ,
CMD_HELP , CMD_EXIT , CMD_CLEAR , CMD_SET_ENV ,
CMD_GET_ENV_ALL , CMD_UNSET_ENV , CMD_GET_ENV , CMD_ADD_PATH ,
CMD_DEL_FILE , CMD_LAUNCH_EXECUTABLE , CMD_KILL , CMD_RESUME ,
CMD_CHILD_PROCESSES , CMD_LIST , CMD_DATE , CMD_TIME ,
CMD_STOP_PROC , CMD_MINIBAT , CMD_LSDIR
}
Possible command types the shell can understand.
Functions
void cmd_init_from_str (struct cmd *obj, const char *str)
Build command from raw input.
void cmd_destroy (struct cmd *obj)
Enumeration Type Documentation
cmd_type
enum cmd_type
Possible command types the shell can understand.
Enumerator
CMD_UNKNOWN
CMD_INVALID_SYNTAX
CMD_NOOP
CMD_CHANGE_DIR
CMD_HELP
CMD_EXIT
CMD_CLEAR
CMD_SET_ENV
CMD_GET_ENV_ALL
CMD_UNSET_ENV
CMD_GET_ENV
CMD_ADD_PATH
CMD_DEL_FILE
CMD_LAUNCH_EXECUTABLE
CMD_KILL
CMD_RESUME
CMD_CHILD_PROCESSES
CMD_LIST
CMD_DATE
CMD_TIME
CMD_STOP_PROC
CMD_MINIBAT
CMD_LSDIR
Definition at line 9 of file cmd.h.
              {
    CMD_UNKNOWN,
    CMD_INVALID_SYNTAX,
    CMD_NOOP,
    CMD_CHANGE_DIR,
    CMD_HELP,
    CMD_EXIT,
    CMD_CLEAR,
    CMD_SET_ENV,
    CMD_GET_ENV_ALL,
    CMD_UNSET_ENV,
    CMD_GET_ENV,
    CMD_ADD_PATH,
    CMD_DEL_FILE,
    CMD_LAUNCH_EXECUTABLE,
    CMD_KILL,
    CMD_RESUME,
    CMD_CHILD_PROCESSES,
    CMD_LIST,
    CMD_DATE,
    CMD_TIME,
    CMD_STOP_PROC,
    CMD_MINIBAT,
    CMD_LSDIR,
};
Function Documentation
cmd_destroy()
void cmd_destroy (struct cmd * obj)
Definition at line 194 of file cmd.c.
{
    switch(obj->type) {
    case CMD_CHANGE_DIR:
        free(obj->val.new_dir);
        break;
    case CMD_SET_ENV:
    case CMD_UNSET_ENV:
    case CMD_GET_ENV:
        free(obj->val.env.name);
        free(obj->val.env.val);
        break;
    case CMD_ADD_PATH:
        free(obj->val.new_path);
        break;
    case CMD_DEL_FILE:
        free(obj->val.filename);
        break;
    case CMD_LSDIR:
        free(obj->val.dir);
        break;
    case CMD_MINIBAT:
    case CMD_LAUNCH_EXECUTABLE:
        args_destroy(&(obj->val.args));
        break;
    default:
        break;
    }
}
References args_destroy(), CMD_ADD_PATH, CMD_CHANGE_DIR, CMD_DEL_FILE, CMD_GET_ENV, CMD_LAUNCH_EXECUTABLE, CMD_LSDIR, CMD_MINIBAT, CMD_SET_ENV, CMD_UNSET_ENV, cmd::type, and cmd::val.
Referenced by main().
cmd_init_from_str()
void cmd_init_from_str (struct cmd * obj, const char * str)
Build command from raw input.
Definition at line 19 of file cmd.c.
{
    assert(res && "NULL input");
    res->type = CMD_UNKNOWN;
    struct args arguments;
    const bool valid = args_init_from_str(&arguments, str);
    if(!valid) {
        res->type = CMD_NOOP;
        return;
    }
    if(arguments.argc == 0) {
        args_destroy(&arguments);
        res->type = CMD_NOOP;
        return;
    }
    const char *name = arguments.argv[0];
    if(strcmp(name, "help") == 0) {
        res->type = CMD_HELP;
    } else if(strcmp(name, "list") == 0) {
        res->type = CMD_LIST;
    } else if(strcmp(name, "date") == 0) {
        res->type = CMD_DATE;
    } else if(strcmp(name, "time") == 0) {
        res->type = CMD_TIME;
    } else if(strcmp(name, "stop") == 0) {
        if(arguments.argc != 2 || !is_number(arguments.argv[1])) {
            format_usage("stop <process id>\n");
            res->type = CMD_NOOP;
        } else {
            res->type = CMD_STOP_PROC;
            res->val.proc_id = atoi(arguments.argv[1]);
        }
    } else if(strcmp(name, "exit") == 0) {
        res->type = CMD_EXIT;
    } else if(strcmp(name, "cd") == 0) {
        res->type = CMD_CHANGE_DIR;
        if(arguments.argc != 2) {
            format_usage("cd <destination dir>\n");
            res->type = CMD_NOOP;
        } else {
            const unsigned int len = strlen(arguments.argv[1]);
            res->val.new_dir = malloc(len + 1);
            memcpy(res->val.new_dir, arguments.argv[1], len);
            res->val.new_dir[len] = '\0';
        }
    } else if(strcmp(name, "clear") == 0) {
        res->type = CMD_CLEAR;
    } else if(strcmp(name, "set") == 0) {
        if(arguments.argc < 2 || arguments.argc > 3) {
            format_usage("set <VAR> <value>\n");
            res->type = CMD_NOOP;
        } else if(arguments.argc == 2) {
            res->type = CMD_SET_ENV;
            const unsigned int name_len = strlen(arguments.argv[1]);
            res->val.env.name = malloc(name_len + 1);
            memcpy(res->val.env.name, arguments.argv[1], name_len);
            res->val.env.name[name_len] = '\0';
            res->val.env.val = NULL;
        } else if(arguments.argc == 3) {
            res->type = CMD_SET_ENV;
            const unsigned int name_len = strlen(arguments.argv[1]);
            res->val.env.name = malloc(name_len + 1);
            memcpy(res->val.env.name, arguments.argv[1], name_len);
            res->val.env.name[name_len] = '\0';
            const unsigned int val_len = strlen(arguments.argv[2]);
            res->val.env.val = malloc(val_len + 1);
            memcpy(res->val.env.val, arguments.argv[2], val_len);
            res->val.env.val[val_len] = '\0';
        }
    } else if(strcmp(name, "unset") == 0) {
        if(arguments.argc != 2) {
            format_usage("unset <VAR>\n");
            res->type = CMD_NOOP;
        } else {
            res->type = CMD_UNSET_ENV;
            const unsigned int len = strlen(arguments.argv[1]);
            res->val.env.name = malloc(len + 1);
            memcpy(res->val.env.name, arguments.argv[1], len);
            res->val.env.name[len] = '\0';
            res->val.env.val = NULL;
        }
    } else if(strcmp(name, "env") == 0) {
        if(arguments.argc == 1) {
            res->type = CMD_GET_ENV_ALL;
        } else if(arguments.argc == 2) {
            res->type = CMD_GET_ENV;
            const unsigned int len = strlen(arguments.argv[1]);
            res->val.env.name = malloc(len + 1);
            memcpy(res->val.env.name, arguments.argv[1], len);
            res->val.env.name[len] = '\0';
            res->val.env.val = NULL;
        } else {
            format_usage("env [VAR]\n");
            res->type = CMD_NOOP;
        }
    } else if(strcmp(name, "kill") == 0) {
        if(arguments.argc != 2 || !is_number(arguments.argv[1])) {
            format_usage("kill <process id>\n");
            res->type = CMD_NOOP;
        } else {
            res->type = CMD_KILL;
            res->val.proc_id = atoi(arguments.argv[1]);
        }
    } else if(strcmp(name, "resume") == 0) {
        if(arguments.argc != 2 || !is_number(arguments.argv[1])) {
            format_usage("resume <process id>\n");
            res->type = CMD_NOOP;
        } else {
            res->type = CMD_RESUME;
            res->val.proc_id = atoi(arguments.argv[1]);
        }
    } else if(strcmp(name, "child") == 0) {
        if(arguments.argc != 2 || !is_number(arguments.argv[1])) {
            format_usage("child <process id>\n");
            res->type = CMD_NOOP;
        } else {
            res->type = CMD_CHILD_PROCESSES;
            res->val.proc_id = atoi(arguments.argv[1]);
        }
    } else if(strcmp(name, "addpath") == 0) {
        if(arguments.argc != 2) {
            format_usage("addpath <new path>\n");
            res->type = CMD_NOOP;
        } else {
            res->type = CMD_ADD_PATH;
            const size_t len = strlen(arguments.argv[1]);
            res->val.new_path = (os_char *)malloc((len + 1) * sizeof(os_char));
            res->val.new_path[len] = '\0';
            memcpy(res->val.new_path, arguments.argv[1], strlen(arguments.argv[1]) * sizeof(os_char));
        }
    } else if(strcmp(name, "delete") == 0) {
        if(arguments.argc > 2 || arguments.argc < 2) {
            format_usage("delete <path to file>\n");
            res->type = CMD_NOOP;
        } else {
            res->type = CMD_DEL_FILE;
            const unsigned int dir_len = strlen(arguments.argv[1]);
            res->val.filename = malloc(dir_len + 1);
            memcpy(res->val.filename, arguments.argv[1], dir_len);
            res->val.filename[dir_len] = '\0';
        }
    } else if(strcmp(name, "lsdir") == 0) {
        if(arguments.argc != 2) {
            format_usage("Usage: lsdir <dir>\n");
            res->type = CMD_NOOP;
        } else {
            res->type = CMD_LSDIR;
            const unsigned int dir_len = strlen(arguments.argv[1]);
            res->val.dir = malloc(dir_len + 1);
            memcpy(res->val.dir, arguments.argv[1], dir_len);
            res->val.dir[dir_len] = '\0';
        }
    } else if(arguments.argc && is_minibat_file(arguments.argv[0])) {
        if(arguments.argc != 1) {
            format_error("Too many arguments\n");
            res->type = CMD_INVALID_SYNTAX;
        } else {
            res->type = CMD_MINIBAT;
            args_deep_copy_init(&res->val.args, &arguments);
        }
    } else {
        res->type = CMD_LAUNCH_EXECUTABLE;
        args_deep_copy_init(&res->val.args, &arguments);
    }
    args_destroy(&arguments);
}
References args::argc, args_deep_copy_init(), args_destroy(), args_init_from_str(), args::argv, CMD_ADD_PATH, CMD_CHANGE_DIR, CMD_CHILD_PROCESSES, CMD_CLEAR, CMD_DATE, CMD_DEL_FILE, CMD_EXIT, CMD_GET_ENV, CMD_GET_ENV_ALL, CMD_HELP, CMD_INVALID_SYNTAX, CMD_KILL, CMD_LAUNCH_EXECUTABLE, CMD_LIST, CMD_LSDIR, CMD_MINIBAT, CMD_NOOP, CMD_RESUME, CMD_SET_ENV, CMD_STOP_PROC, CMD_TIME, CMD_UNKNOWN, CMD_UNSET_ENV, format_error(), format_usage(), is_minibat_file(), is_number(), cmd::type, and cmd::val.
Referenced by scan_input().