tiny-shell: source/runner/datetime.h File Reference
datetime.h File Reference
#include "../os/operations.h"
#include "res.h"
Functions
enum run_result run_get_time ()
get time
enum run_result run_get_date ()
get date
Function Documentation
run_get_date()
enum run_result run_get_date ()
get date
Definition at line 7 of file datetime.c.
{
    return get_date() ? RUN_OK : RUN_FAILED;
}
References get_date(), RUN_FAILED, and RUN_OK.
Referenced by invoke_runner().
run_get_time()
enum run_result run_get_time ()
get time
Definition at line 3 of file datetime.c.
{
    return get_time() ? RUN_OK : RUN_FAILED;
}
References get_time(), RUN_FAILED, and RUN_OK.
Referenced by invoke_runner().