tiny-shell: source/runner/env.c File Reference
env.c File Reference
#include "env.h"
#include "../core/config.h"
#include "../core/io_wrap.h"
#include "../os/operations.h"
#include <stdlib.h>
Functions
enum run_result run_set_env (const os_char *name, const os_char *val)
Set current process's environment variable.
enum run_result run_unset_env (const os_char *name)
Unset current process's environment variable.
enum run_result run_get_all_env ()
Set current process's environment variable.
enum run_result run_get_env (const os_char *name)
Set current process's environment variable.
Function Documentation
run_get_all_env()
enum run_result run_get_all_env ()
Set current process's environment variable.
Definition at line 15 of file env.c.
{
    os_char *env = get_all_shell_env_display();
    if(!env) {
        return RUN_FAILED;
    } else {
        format_output("%s\n", env);
        free(env);
        return RUN_OK;
    }
}
References format_output(), get_all_shell_env_display(), RUN_FAILED, and RUN_OK.
Referenced by invoke_runner().
run_get_env()
enum run_result run_get_env (const os_char * name)
Set current process's environment variable.
Definition at line 26 of file env.c.
{
    os_char buffer[ENV_VAR_BUFFER_SIZE];
    if(!get_shell_env(name, ENV_VAR_BUFFER_SIZE, buffer)) {
        return RUN_FAILED;
    }
    format_output("%s\n", buffer);
    return RUN_OK;
}
References ENV_VAR_BUFFER_SIZE, format_output(), get_shell_env(), RUN_FAILED, and RUN_OK.
Referenced by invoke_runner().
run_set_env()
enum run_result run_set_env (const os_char * name, const os_char * val)
Set current process's environment variable.
Definition at line 7 of file env.c.
{
    return set_shell_env(name, val) ? RUN_OK : RUN_FAILED;
}
References RUN_FAILED, RUN_OK, and set_shell_env().
Referenced by invoke_runner().
run_unset_env()
enum run_result run_unset_env (const os_char * name)
Unset current process's environment variable.
Definition at line 11 of file env.c.
{
    return unset_shell_env(name) ? RUN_OK : RUN_FAILED;
}
References RUN_FAILED, RUN_OK, and unset_shell_env().
Referenced by invoke_runner().