tiny-shell: source/runner/invoke.h File Reference
invoke.h File Reference
#include "../core/cmd.h"
#include "res.h"
Functions
enum run_result invoke_runner (const struct cmd *cmd)
Invoke corresponding functions based on cmd's type and value.
Function Documentation
invoke_runner()
enum run_result invoke_runner (const struct cmd * cmd)
Invoke corresponding functions based on cmd's type and value.
Returns
Result of the operation
Definition at line 22 of file invoke.c.
{
    switch(cmd->type) {
    case CMD_HELP:
        return run_help();
    case CMD_EXIT:
        format_success("%s", "Goodbye\n");
        return RUN_EXIT;
    case CMD_CHANGE_DIR:
        return run_cd(cmd->val.new_dir);
    case CMD_DEL_FILE:
        return run_del(cmd->val.filename);
    case CMD_CLEAR:
        clear_screen();
        return RUN_OK;
    case CMD_LSDIR:
        return run_lsdir(cmd->val.dir);
    case CMD_LIST:
        return run_get_list_process();
    case CMD_TIME:
        return run_get_time();
    case CMD_DATE:
        return run_get_date();
    case CMD_STOP_PROC:
        return run_stop(cmd->val.proc_id);
    case CMD_LAUNCH_EXECUTABLE:
        return run_launch_executable(cmd->val.args);
    case CMD_KILL:
        return run_kill(cmd->val.proc_id);
    case CMD_ADD_PATH:
        return run_add_path(cmd->val.new_path);
    case CMD_MINIBAT:
        return run_minibat(cmd->val.args);
    case CMD_SET_ENV:
        return run_set_env(cmd->val.env.name, cmd->val.env.val);
    case CMD_UNSET_ENV:
        return run_unset_env(cmd->val.env.name);
    case CMD_GET_ENV_ALL:
        return run_get_all_env();
    case CMD_GET_ENV:
        return run_get_env(cmd->val.env.name);
    case CMD_UNKNOWN:
        format_success("%s", "Unknown command. Use \"help\" for more information\n");
        return RUN_FAILED;
    case CMD_NOOP:
        return RUN_OK;
    case CMD_INVALID_SYNTAX:
        format_success("%s", "Invalid syntax. Use \"help\" for more information\n");
        return RUN_FAILED;
    case CMD_RESUME:
        return run_resume(cmd->val.proc_id);
    case CMD_CHILD_PROCESSES:
        return run_child_processes(cmd->val.proc_id);
    default:
        assert(false && "unimplemented command");
        return RUN_FAILED;
    }
}
References clear_screen(), CMD_ADD_PATH, CMD_CHANGE_DIR, CMD_CHILD_PROCESSES, CMD_CLEAR, CMD_DATE, CMD_DEL_FILE, CMD_EXIT, CMD_GET_ENV, CMD_GET_ENV_ALL, CMD_HELP, CMD_INVALID_SYNTAX, CMD_KILL, CMD_LAUNCH_EXECUTABLE, CMD_LIST, CMD_LSDIR, CMD_MINIBAT, CMD_NOOP, CMD_RESUME, CMD_SET_ENV, CMD_STOP_PROC, CMD_TIME, CMD_UNKNOWN, CMD_UNSET_ENV, format_success(), run_add_path(), run_cd(), run_child_processes(), run_del(), RUN_EXIT, RUN_FAILED, run_get_all_env(), run_get_date(), run_get_env(), run_get_list_process(), run_get_time(), run_help(), run_kill(), run_launch_executable(), run_lsdir(), run_minibat(), RUN_OK, run_resume(), run_set_env(), run_stop(), run_unset_env(), cmd::type, and cmd::val.
Referenced by main().