tiny-shell: source/core/io_wrap.c File Reference
io_wrap.c File Reference
#include "io_wrap.h"
#include "../os/operations.h"
#include "config.h"
#include "utils.h"
#include <assert.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdio.h>
Macros
#define COLOR_GREEN "\033[32m"
#define COLOR_YELLOW "\033[33m"
#define COLOR_RED "\033[31m"
#define COLOR_BLUE "\033[34m"
#define COLOR_BLACK "\033[30m"
Functions
enum run_result * last_run_status ()
void io_set_last_status (enum run_result result)
Set the result of last command (RUN_OK/RUN_FAIL/...)
bool * is_prompt_visible ()
void io_set_prompt_visibility (bool visible)
Config if prompt should be printed.
void prompt_input ()
void scan_input (struct cmd *obj)
Ask and convert user's input into command.
void format_usage (char *fmt,...)
Used format_xxx instead of printf and such for uniform output.
void format_success (char *fmt,...)
Used format_xxx instead of printf and such for uniform output.
void format_output (char *fmt,...)
Used format_xxx instead of printf and such for uniform output.
void format_error (char *fmt,...)
Used format_xxx instead of printf and such for uniform output.
Macro Definition Documentation
COLOR_BLACK
#define COLOR_BLACK "\033[30m"
Definition at line 15 of file io_wrap.c.
Referenced by format_error(), format_output(), format_success(), format_usage(), and prompt_input().
COLOR_BLUE
#define COLOR_BLUE "\033[34m"
Definition at line 14 of file io_wrap.c.
Referenced by prompt_input().
COLOR_GREEN
#define COLOR_GREEN "\033[32m"
Definition at line 11 of file io_wrap.c.
Referenced by format_success().
COLOR_RED
#define COLOR_RED "\033[31m"
Definition at line 13 of file io_wrap.c.
Referenced by format_error(), and prompt_input().
COLOR_YELLOW
#define COLOR_YELLOW "\033[33m"
Definition at line 12 of file io_wrap.c.
Referenced by format_usage().
Function Documentation
format_error()
void format_error (char * fmt, ...)
Used format_xxx instead of printf and such for uniform output.
Definition at line 78 of file io_wrap.c.
{
    if(support_color())
        printf(COLOR_RED);
    printf("ERR: ");
    va_list argptr; // NOLINT
    va_start(argptr, fmt);
    vfprintf(stdout, fmt, argptr);
    va_end(argptr);
    if(support_color())
        printf(COLOR_BLACK);
}
References COLOR_BLACK, COLOR_RED, and support_color().
Referenced by add_path(), cmd_init_from_str(), main(), split_by_whitespaces(), and transform_quotes().
format_output()
void format_output (char * fmt, ...)
Used format_xxx instead of printf and such for uniform output.
Definition at line 69 of file io_wrap.c.
{
    if(support_color())
        printf(COLOR_BLACK);
    va_list argptr; // NOLINT
    va_start(argptr, fmt);
    vfprintf(stdout, fmt, argptr);
    va_end(argptr);
}
References COLOR_BLACK, and support_color().
Referenced by run_get_all_env(), run_get_env(), and run_help().
format_success()
void format_success (char * fmt, ...)
Used format_xxx instead of printf and such for uniform output.
Definition at line 58 of file io_wrap.c.
{
    if(support_color())
        printf(COLOR_GREEN);
    va_list argptr; // NOLINT
    va_start(argptr, fmt);
    vfprintf(stdout, fmt, argptr);
    va_end(argptr);
    if(support_color())
        printf(COLOR_BLACK);
}
References COLOR_BLACK, COLOR_GREEN, and support_color().
Referenced by add_path(), invoke_runner(), and main().
format_usage()
void format_usage (char * fmt, ...)
Used format_xxx instead of printf and such for uniform output.
Definition at line 46 of file io_wrap.c.
{
    if(support_color())
        printf(COLOR_YELLOW);
    printf("USAGE: ");
    va_list argptr; // NOLINT
    va_start(argptr, fmt);
    vfprintf(stdout, fmt, argptr);
    va_end(argptr);
    if(support_color())
        printf(COLOR_BLACK);
}
References COLOR_BLACK, COLOR_YELLOW, and support_color().
Referenced by cmd_init_from_str().
io_set_last_status()
void io_set_last_status (enum run_result result)
Set the result of last command (RUN_OK/RUN_FAIL/...)
Definition at line 22 of file io_wrap.c.
{
    *last_run_status() = result;
}
References last_run_status().
Referenced by main().
io_set_prompt_visibility()
void io_set_prompt_visibility (bool visible)
Config if prompt should be printed.
Definition at line 31 of file io_wrap.c.
{
    *is_prompt_visible() = visible;
}
References is_prompt_visible().
Referenced by main().
is_prompt_visible()
bool * is_prompt_visible ()
Definition at line 26 of file io_wrap.c.
{
    static bool visible = true;
    return &visible;
}
Referenced by io_set_prompt_visibility(), and prompt_input().
last_run_status()
enum run_result * last_run_status ()
Definition at line 17 of file io_wrap.c.
{
    static enum run_result res = RUN_OK;
    return &res;
}
References RUN_OK.
Referenced by io_set_last_status(), and prompt_input().
prompt_input()
void prompt_input ()
Definition at line 90 of file io_wrap.c.
                    {
    os_char buffer[CWD_BUFFER_SIZE];
    get_cwd(CWD_BUFFER_SIZE, buffer);
    if(!*is_prompt_visible()) {
        return;
    }
    switch(*last_run_status()) {
    case RUN_OK:
        if(support_color())
            printf(COLOR_BLUE);
        printf("%s\n-> ", buffer);
        break;
    case RUN_EXIT:
        break;
    case RUN_FAILED:
        if(support_color())
            printf(COLOR_BLUE "%s\n" COLOR_RED ":( -> ", buffer);
        else
            printf("%s\n:( -> ", buffer);
        break;
    default:
        assert(false && "unimplemented");
    }
    if(support_color()) {
        printf(COLOR_BLACK);
    }
}
References COLOR_BLACK, COLOR_BLUE, COLOR_RED, CWD_BUFFER_SIZE, get_cwd(), is_prompt_visible(), last_run_status(), RUN_EXIT, RUN_FAILED, RUN_OK, and support_color().
Referenced by scan_input().
scan_input()
void scan_input (struct cmd * obj)
Ask and convert user's input into command.
Definition at line 36 of file io_wrap.c.
{
    prompt_input();
    char buffer[INPUT_BUFFER_SIZE] = {0};
    if(!fgets(buffer, INPUT_BUFFER_SIZE, stdin)) {
        cmd_init_from_str(obj, "exit");
    } else {
        cmd_init_from_str(obj, buffer);
    }
}
References cmd_init_from_str(), INPUT_BUFFER_SIZE, and prompt_input().
Referenced by main().