tiny-shell: source/core/io_wrap.h File Reference
io_wrap.h File Reference
#include <stdbool.h>
#include "../runner/res.h"
#include "cmd.h"
Functions
void io_set_last_status (enum run_result result)
Set the result of last command (RUN_OK/RUN_FAIL/...)
void io_set_text_white ()
Set default text color to white.
void io_set_prompt_visibility (bool visible)
Config if prompt should be printed.
void scan_input (struct cmd *obj)
Ask and convert user's input into command.
void format_success (char *fmt,...)
Used format_xxx instead of printf and such for uniform output.
void format_output (char *fmt,...)
Used format_xxx instead of printf and such for uniform output.
void format_usage (char *fmt,...)
Used format_xxx instead of printf and such for uniform output.
void format_error (char *fmt,...)
Used format_xxx instead of printf and such for uniform output.
Function Documentation
format_error()
void format_error (char * fmt, ...)
Used format_xxx instead of printf and such for uniform output.
Definition at line 89 of file io_wrap.c.
{
    if(support_color())
        printf(COLOR_RED);
    printf("ERR: ");
    va_list argptr; // NOLINT
    va_start(argptr, fmt);
    vfprintf(stdout, fmt, argptr);
    va_end(argptr);
    if(support_color())
        printf(COLOR_DEFAULT);
}
References COLOR_DEFAULT, COLOR_RED, and support_color().
Referenced by add_path(), cmd_init_from_str(), main(), split_by_whitespaces(), and transform_quotes().
format_output()
void format_output (char * fmt, ...)
Used format_xxx instead of printf and such for uniform output.
Definition at line 80 of file io_wrap.c.
{
    if(support_color())
        printf(COLOR_DEFAULT);
    va_list argptr; // NOLINT
    va_start(argptr, fmt);
    vfprintf(stdout, fmt, argptr);
    va_end(argptr);
}
References COLOR_DEFAULT, and support_color().
Referenced by run_get_all_env(), run_get_env(), and run_help().
format_success()
void format_success (char * fmt, ...)
Used format_xxx instead of printf and such for uniform output.
Definition at line 69 of file io_wrap.c.
{
    if(support_color())
        printf(COLOR_GREEN);
    va_list argptr; // NOLINT
    va_start(argptr, fmt);
    vfprintf(stdout, fmt, argptr);
    va_end(argptr);
    if(support_color())
        printf(COLOR_DEFAULT);
}
References COLOR_DEFAULT, COLOR_GREEN, and support_color().
Referenced by add_path(), invoke_runner(), and main().
format_usage()
void format_usage (char * fmt, ...)
Used format_xxx instead of printf and such for uniform output.
Definition at line 57 of file io_wrap.c.
{
    if(support_color())
        printf(COLOR_YELLOW);
    printf("USAGE: ");
    va_list argptr; // NOLINT
    va_start(argptr, fmt);
    vfprintf(stdout, fmt, argptr);
    va_end(argptr);
    if(support_color())
        printf(COLOR_DEFAULT);
}
References COLOR_DEFAULT, COLOR_YELLOW, and support_color().
Referenced by cmd_init_from_str().
io_set_last_status()
void io_set_last_status (enum run_result result)
Set the result of last command (RUN_OK/RUN_FAIL/...)
Definition at line 29 of file io_wrap.c.
{
    *last_run_status() = result;
}
References last_run_status().
Referenced by main().
io_set_prompt_visibility()
void io_set_prompt_visibility (bool visible)
Config if prompt should be printed.
Definition at line 42 of file io_wrap.c.
{
    *is_prompt_visible() = visible;
}
References is_prompt_visible().
Referenced by main().
io_set_text_white()
void io_set_text_white ()
Set default text color to white.
Definition at line 33 of file io_wrap.c.
{
    *io_use_white_text() = true;
}
References io_use_white_text().
Referenced by main().
scan_input()
void scan_input (struct cmd * obj)
Ask and convert user's input into command.
Definition at line 47 of file io_wrap.c.
{
    prompt_input();
    char buffer[INPUT_BUFFER_SIZE] = {0};
    if(!fgets(buffer, INPUT_BUFFER_SIZE, stdin)) {
        cmd_init_from_str(obj, "exit");
    } else {
        cmd_init_from_str(obj, buffer);
    }
}
References cmd_init_from_str(), INPUT_BUFFER_SIZE, and prompt_input().
Referenced by main().