tiny-shell: source/core/utils.h File Reference
utils.h File Reference
#include <stdbool.h>
Functions
bool is_number (const char *c)
bool support_color ()
Function Documentation
is_number()
bool is_number (const char * c)
Definition at line 8 of file utils.c.
{
    if(c == NULL || c[0] == '\0')
        return false;
    const unsigned int length = strlen(c);
    static const unsigned int MAX_INT_DIGITS = 10;
    if(length > MAX_INT_DIGITS)
        return false;
    for(int i = 0; i < length; ++i) {
        if(c[i] < '0' || c[i] > '9')
            return false;
    }
    return true;
}
Referenced by cmd_init_from_str().
support_color()
bool support_color ()
Definition at line 56 of file utils.c.
                     {
    static bool res = false;
    static bool checked = false;
    if(!checked) {
        res = priv_support_color();
        checked = true;
    }
    return res;
}
Referenced by format_error(), format_output(), format_success(), format_usage(), and prompt_input().